### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by denisbetsi** [herenow/crate-connect#2]
When there are too many outstanding commands the library terminates ungracefully. Here's the trace log 

`
Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)
---------------------------------------------
    at Socket.Readable.on (_stream_readable.js:687:35)
    at tickOnSocket (_http_client.js:560:10)
    at onSocketNT (_http_client.js:580:5)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
---------------------------------------------
    at ClientRequest.onSocket (_http_client.js:572:11)
    at _http_agent.js:164:11
    at oncreate (_http_agent.js:235:5)
    at Agent.createSocket (_http_agent.js:197:5)
    at Agent.addRequest (_http_agent.js:157:10)
    at new ClientRequest (_http_client.js:160:16)
    at Object.exports.request (http.js:31:10)
    at Contructor.Send [as queryPost] (/SMS/node_modules/crate-connect/src/connect.query.js:21:21)
    at Select.Run (/SMS/node_modules/cratejs/src/select.js:58:22)
`

**Comment by denisbetsi** [comment]
Adding this

`

		var maxRetries = 3;

		request.on('error', function(e) {
			if(retry<maxRetries){
				// Try again
				Query.send(query,statements,callback,retry+1);
			}else{
				callback(e, null);
			}
		    request.abort();
		});

`

to 

connect.query.js

Cures that issue, instead of dying completely. it'll retry up to 3 times and if it errors out, it exits gracefully instead of crashing entire app.
